<a href="https://colab.research.google.com/github/jsrader77014/MachineLearing/blob/master/Numpy/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Create NumPy arrays using Python's "array like" data types</h1>


In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.5


In [5]:
mylist = [-17,0,4,5,9]
my_array_from_list = np.array(mylist)
my_array_from_list

array([-17,   0,   4,   5,   9])

In [6]:
my_array_from_list*10

array([-170,    0,   40,   50,   90])

In [9]:
my_tuple =(14,-3.54,5+7)
np.array(my_tuple)


array([14.  , -3.54, 12.  ])

### Diffrence between python and nupy data structures

In [10]:
my_tuple * 6

(14,
 -3.54,
 12,
 14,
 -3.54,
 12,
 14,
 -3.54,
 12,
 14,
 -3.54,
 12,
 14,
 -3.54,
 12,
 14,
 -3.54,
 12)

In [11]:
np.array(my_tuple) * 6

array([ 84.  , -21.24,  72.  ])