<a href="https://colab.research.google.com/github/jsrader77014/MachineLearing/blob/master/Numpy/Boolean.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Boolean Mask Arrays

In [1]:
import numpy as np

In [2]:
my_vector = np.array([-17, -4, 0, 2, 21, 37, 105])
my_vector

array([-17,  -4,   0,   2,  21,  37, 105])

In [3]:
zero_mod_7_mask = 0 ==(my_vector % 7)
zero_mod_7_mask


array([False, False,  True, False,  True, False,  True])

In [4]:
sub_array = my_vector[zero_mod_7_mask]
sub_array

array([  0,  21, 105])

In [7]:
sub_array[sub_array>0]

array([ 21, 105])

# NumPy logical operators

In [8]:
mod_test = 0 ==(my_vector % 7)
positive_test = my_vector > 0

In [12]:
combined_mask = np.logical_and(mod_test,positive_test)
combined_mask

array([False, False, False, False,  True, False,  True])

In [13]:
my_vector[combined_mask]

array([ 21, 105])