<a href="https://colab.research.google.com/github/jsrader77014/MachineLearing/blob/master/Numpy/Broadcasting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Broadcasting</h1>

In [1]:
import numpy as np

In [2]:
my_3D_array = np.arange(70)
my_3D_array.shape = (2,7,5)
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [4]:
#shape
my_3D_array.shape

(2, 7, 5)

In [6]:
#number of dimensions
my_3D_array.ndim

3

In [7]:
#size
my_3D_array.size

70

In [8]:
#data type for each element
my_3D_array.dtype

dtype('int64')

In [9]:
5 * my_3D_array -2

array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [20]:
left_mat = np.arange(6).reshape((2,3))
right_mat = np.arange(15).reshape((3,5))
print(left_mat)
print(right_mat)

[[0 1 2]
 [3 4 5]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [21]:
np.inner(left_mat,right_mat)

ValueError: ignored

In [22]:
np.dot(left_mat,right_mat)

array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

###Operations along axes

In [23]:
my_3D_array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34]],

       [[35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59],
        [60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]]])

In [24]:
my_3D_array.shape

(2, 7, 5)

In [25]:
my_3D_array.sum()

2415

$\frac{n(n+1)}{2}$


In [33]:
n = 69
(n*(n+1))/2

2415.0

In [34]:
my_3D_array.sum(axis=0)

array([[ 35,  37,  39,  41,  43],
       [ 45,  47,  49,  51,  53],
       [ 55,  57,  59,  61,  63],
       [ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103]])

In [36]:
my_3D_array.sum(axis=1)

array([[105, 112, 119, 126, 133],
       [350, 357, 364, 371, 378]])

In [37]:
my_3D_array.sum(axis=2)

array([[ 10,  35,  60,  85, 110, 135, 160],
       [185, 210, 235, 260, 285, 310, 335]])

# Broadcasting Rules

In [40]:
my_2D_array = np.ones(35, dtype='int_').reshape((7,5)) *3
my_2D_array

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [42]:
my_random_2D_array = np.random.random((7,5))
my_random_2D_array

array([[0.48667517, 0.33978467, 0.94593296, 0.10729277, 0.89294936],
       [0.6824016 , 0.67929476, 0.29170735, 0.84491741, 0.62414833],
       [0.75220717, 0.96627972, 0.87503287, 0.9199312 , 0.25244318],
       [0.28635125, 0.59306734, 0.06106292, 0.32057059, 0.42692292],
       [0.71075133, 0.2685559 , 0.86247537, 0.61116563, 0.52975732],
       [0.44852627, 0.3127697 , 0.78137267, 0.88877432, 0.51655276],
       [0.87066803, 0.8666667 , 0.40636905, 0.97783931, 0.57942117]])

In [45]:
np.set_printoptions(precision=4)
my_3D_array * my_random_2D_array

array([[[ 0.    ,  0.3398,  1.8919,  0.3219,  3.5718],
        [ 3.412 ,  4.0758,  2.042 ,  6.7593,  5.6173],
        [ 7.5221, 10.6291, 10.5004, 11.9591,  3.5342],
        [ 4.2953,  9.4891,  1.0381,  5.7703,  8.1115],
        [14.215 ,  5.6397, 18.9745, 14.0568, 12.7142],
        [11.2132,  8.132 , 21.0971, 24.8857, 14.98  ],
        [26.12  , 26.8667, 13.0038, 32.2687, 19.7003]],

       [[17.0336, 12.2322, 34.9995,  4.0771, 34.825 ],
        [27.2961, 27.8511, 12.2517, 36.3314, 27.4625],
        [33.8493, 44.4489, 41.1265, 44.1567, 12.3697],
        [14.3176, 30.2464,  3.1753, 16.9902, 23.0538],
        [39.0913, 15.0391, 49.1611, 35.4476, 31.2557],
        [26.9116, 19.079 , 48.4451, 55.9928, 33.0594],
        [56.5934, 57.2   , 27.2267, 66.4931, 39.9801]]])

In [48]:
my_vector = np.arange(5)*7
my_vector[0]=-1
my_vector

array([-1,  7, 14, 21, 28])

In [49]:
my_3D_array/my_vector

array([[[ -0.    ,   0.1429,   0.1429,   0.1429,   0.1429],
        [ -5.    ,   0.8571,   0.5   ,   0.381 ,   0.3214],
        [-10.    ,   1.5714,   0.8571,   0.619 ,   0.5   ],
        [-15.    ,   2.2857,   1.2143,   0.8571,   0.6786],
        [-20.    ,   3.    ,   1.5714,   1.0952,   0.8571],
        [-25.    ,   3.7143,   1.9286,   1.3333,   1.0357],
        [-30.    ,   4.4286,   2.2857,   1.5714,   1.2143]],

       [[-35.    ,   5.1429,   2.6429,   1.8095,   1.3929],
        [-40.    ,   5.8571,   3.    ,   2.0476,   1.5714],
        [-45.    ,   6.5714,   3.3571,   2.2857,   1.75  ],
        [-50.    ,   7.2857,   3.7143,   2.5238,   1.9286],
        [-55.    ,   8.    ,   4.0714,   2.7619,   2.1071],
        [-60.    ,   8.7143,   4.4286,   3.    ,   2.2857],
        [-65.    ,   9.4286,   4.7857,   3.2381,   2.4643]]])