<a href="https://colab.research.google.com/github/jsrader77014/MachineLearing/blob/master/Numpy/linspace.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>linspace(), zeros(), ones(), and NumPy data types</h1>

In [1]:
import numpy as np

In [2]:
np.linspace(5,15,9)

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ])

In [4]:
my_linspace = np.linspace(5,15,9, retstep=True)
my_linspace

(array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  , 11.25, 12.5 , 13.75, 15.  ]), 1.25)

In [7]:
print(my_linspace[0])
print(my_linspace[1])

[ 5.    6.25  7.5   8.75 10.   11.25 12.5  13.75 15.  ]
1.25


# zeros()


In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# ones()

In [9]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.zeros((5,4,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
np.zeros(11,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.zeros(11)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
np.zeros(11,dtype='bool')

array([False, False, False, False, False, False, False, False, False,
       False, False])