<a href="https://colab.research.google.com/github/jsrader77014/MachineLearing/blob/master/Numpy/Structured.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1>Creating Structured Arrays</h1>

In [1]:
import numpy as np

In [2]:
person_data_def = [('name','S6'),('height','f8'),('weight','f8'), ('age', 'i8')]
person_data_def

[('name', 'S6'), ('height', 'f8'), ('weight', 'f8'), ('age', 'i8')]

In [3]:
people_array = np.zeros((4), dtype=person_data_def)

people_array

array([('', 0., 0., 0), ('', 0., 0., 0), ('', 0., 0., 0), ('', 0., 0., 0)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [4]:
people_array[3]=('Delta',73,205,34)
people_array[0]=('Alpha',65,112,23)

people_array

array([('Alpha', 65., 112., 23), ('',  0.,   0.,  0), ('',  0.,   0.,  0),
       ('Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [5]:
people_array[0:]

array([('Alpha', 65., 112., 23), ('',  0.,   0.,  0), ('',  0.,   0.,  0),
       ('Delta', 73., 205., 34)],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [6]:
ages = people_array['age']
ages


array([23,  0,  0, 34])

In [9]:
make_youthful = ages/2
make_youthful


array([11,  0,  0, 17])

# Multi-dimensional Structured Arrays

In [10]:
people_big_array = np.zeros((4,3,2), dtype=person_data_def)
people_big_array

array([[[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]],

       [[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]],

       [[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]],

       [[('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)],
        [('', 0., 0., 0), ('', 0., 0., 0)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [11]:
people_big_array[3,2,1] = ('Echo',68, 155,46)
people_big_array

array([[[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)]],

       [[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)]],

       [[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)]],

       [[('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('',  0.,   0.,  0)],
        [('',  0.,   0.,  0), ('Echo', 68., 155., 46)]]],
      dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [12]:
people_big_array['height']

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0., 68.]]])

In [14]:
people_big_array[['height','weight']]

array([[[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)]],

       [[( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), ( 0.,   0.)],
        [( 0.,   0.), (68., 155.)]]],
      dtype={'names':['height','weight'], 'formats':['<f8','<f8'], 'offsets':[6,14], 'itemsize':30})

# Creating Record Array

In [15]:
person_record_array = np.rec.array([('Delta',73,205,34),('Alpha',65,112,23)],dtype=person_data_def)
person_record_array

rec.array([('Delta', 73., 205., 34), ('Alpha', 65., 112., 23)],
          dtype=[('name', 'S6'), ('height', '<f8'), ('weight', '<f8'), ('age', '<i8')])

In [16]:
person_record_array[0].age

34